version: "3.9"

services:
  start_api:
    depends_on:
      - fill_bdd
    restart: on-failure:15
    build:
      context: .
      dockerfile: dockerfile_api
    ports:
      - "8000:8002"

  fill_bdd:
    depends_on:
      - tm_db
    restart: on-failure:5
    build:
      context: .
      dockerfile: dockerfile_fill_bdd

  tm_db:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_TCP_PORT: 3306
    ports:
      - "3307:3306"




# version: "3.9"

# services:

#   start_bdd:
#     image: local-mysql:latest
#     container_name: sql 
#     ports:
#       - "3306:3306" 

#   fill_bdd:
#     depends_on:
#       - start_bdd           
#     image: bdd:latest
#     container_name: bdd
#     ports:
#       - "3306:3306" 
#   start_api:
#     depends_on:
#       - fill_bdd           
#     image: api:latest
#     container_name: api
#     ports:
#       - "8000:8000" 
