version: "3.9"

services:

  tm_db:
    image: mysql:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_TCP_PORT: 3306
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "tm_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  fill_bdd:
    depends_on:
      tm_db:
        condition: service_healthy
    build:
      context: .
      dockerfile: dockerfile_fill_bdd

  start_api:
    depends_on:
      fill_bdd:
        condition: service_completed_successfully
    restart: on-failure:15
    build:
      context: .
      dockerfile: dockerfile_api
    ports:
      - "8000:8002"


# version: "3.9"

# services:

#   start_bdd:
#     image: local-mysql:latest
#     container_name: sql 
#     ports:
#       - "3306:3306" 

#   fill_bdd:
#     depends_on:
#       - start_bdd           
#     image: bdd:latest
#     container_name: bdd
#     ports:
#       - "3306:3306" 
#   start_api:
#     depends_on:
#       - fill_bdd           
#     image: api:latest
#     container_name: api
#     ports:
#       - "8000:8000" 
