version: "3.9"

services:

  start_bdd:
    image: local-mysql:latest
    container_name: sql 
    ports:
      - "3306:3306" 

  fill_bdd:
    depends_on:
      - start_bdd           
    image: bdd:latest
    container_name: bdd



  start_api:
    depends_on:
      - fill_bdd           
    image: api:latest
    container_name: api
    ports:
      - "8000:8000"  

