version: "3.9"
services:
    # start_api:
    #   depends_on:
    #     - fill_bdd
    #     - db
    #   build: 
    #       context: ./
    #       dockerfile: dockerfile_api          
    #   ports:
    #     - "8002:8002"
    fill_bdd:
        depends_on:
            - tm_db
        #restart: on-failure
        build: 
          context: ./
          dockerfile: dockerfile_tmdb
    tm_db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: DB
            MYSQL_TCP_PORT: 3307
        ports:
          - 3307:3306



# version: "3.9"

# services:

#   start_bdd:
#     image: local-mysql:latest
#     container_name: sql 
#     ports:
#       - "3306:3306" 

#   fill_bdd:
#     depends_on:
#       - start_bdd           
#     image: bdd:latest
#     container_name: bdd
#     ports:
#       - "3306:3306" 
#   start_api:
#     depends_on:
#       - fill_bdd           
#     image: api:latest
#     container_name: api
#     ports:
#       - "8000:8000" 
